# NumPy

In this lesson we will learn the basics of numerical analysis using the NumPy library. 

# Set up

In [3]:
import numpy as np

# Basics

Let's take a took at how to create tensors with NumPy.
*    **Tensor**: collection of values 

In [2]:
t= np.array([6,7])

In [3]:
type(t)

numpy.ndarray

In [48]:
np.array([1+2j, 2, 3], dtype=complex)

array([1.+2.j, 2.+0.j, 3.+0.j])

In [5]:
# Vector
x = np.array([1,2,3])
print ("x: ", x)
print ("x ndim: ", x.ndim) # number of dimensions
print ("x shape:", x.shape) # dimensions
print ("x size: ", x.size) # size of elements
print ("x dtype: ", x.dtype) # data type

x:  [1 2 3]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  int64


In [8]:
# Vector
x = np.array([1.3 , 2.2 , 1.7], dtype=int)
print ("x: ", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype) # notice the int datatype

x:  [1 2 1]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  int64


In [9]:
# Matrix
x = np.array([[1,2], [3,4]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[1 2]
 [3 4]]
x ndim:  2
x shape: (2, 2)
x size:  4
x dtype:  int64


In [5]:
# 3-D Tensor
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape: (2, 2, 2)
x size:  8
x dtype:  int64


NumPy also comes with several functions that allow us to create tensors quickly.

In [11]:
# Functions
print ("np.zeros((2,2)):\n", np.zeros((2,2))) #all zeros
print ("np.ones((2,2)):\n", np.ones((2,2))) #all one
print ("np.eye((2)):\n", np.eye((2))) # identity matrix 
print ("np.random.random((2,2)):\n", np.random.random((2,2)))#matrix with random values between 0 and 1

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.48594315 0.25332842]
 [0.22954126 0.97584114]]


# Indexing and slicing

We can extract specific values from our tensors using indexing.

> Keep in mind that when indexing the row and column, indices start at 0. And like indexing with lists, we can use negative indices as well (where -1 is the last item).

In [15]:
# Indexing
x = np.array([1, 2, 3])
print ("x: ", x)
print ("x[0]: ", x[0])
x[0] = 0 #affect new value
print ("x: ", x)

x:  [1 2 3]
x[0]:  1
x:  [0 2 3]


In [18]:
lst = [i for i in range(10)] #contract way to create a list
x = np.array(lst) 
print("x = {}".format(x)) #new way to create a string 
x[1:-2]

x = [0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Slicing
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print ("x column 1: ", x[:, 1]) #take all rows and the column 1
print ("x row 0: ", x[0, :]) #take  row 0 and all columns
print ("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3]) #take rows 0 and 1, and columns 1 and 2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


In [21]:
# Integer array indexing
print (x)
rows_to_get = np.array([0, 1, 2])
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
# Combine sequences above to get values to get
print ("indexed values: ", x[rows_to_get, cols_to_get]) # (0, 0), (1, 2), (2, 1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [23]:
# Boolean array indexing
x = np.array([[1, 2], [3, 4], [5, 6]])
print ("x:\n", x)
print ("x > 2:\n", x > 2) #create a boolean matrix with the same shape as x, put True where x[i,j] is greater than 2,and false otherwise
print ("x[x > 2]:\n", x[x > 2]) #take all value from where x>2 values were True

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


# Arithmetic


In [25]:
# Basic math
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or x * y

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


## Dot product

One of the most common NumPy operations we’ll use in data analysis is matrix multiplication using the dot product. We take the rows of our first matrix (2) and the columns of our second matrix (2) to determine the dot product, giving us an output of `[2 X 2]`. The only requirement is that the inside dimensions match, in this case the first matrix has 3 columns and the second matrix has 3 rows. 

<div>
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/foundations/numpy/dot.gif" width="450">
</div>

In [30]:
# Dot product
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # we can specify dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
c = a.dot(b)
print("a=",a)
print("b=",b)
print (f"{a.shape} · {b.shape} = {c.shape}")
print ("a.dot(b)= \n",c)

a= [[1. 2. 3.]
 [4. 5. 6.]]
b= [[ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
(2, 3) · (3, 2) = (2, 2)
a.dot(b)= 
 [[ 58.  64.]
 [139. 154.]]


## Axis operations

We can also do operations across a specific axis.

In [31]:
# Sum across a dimension
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum axis=0: ", np.sum(x, axis=0)) # sum across rows
print ("sum axis=1: ", np.sum(x, axis=1)) # sum across columns

[[1 2]
 [3 4]]
sum all:  10
sum axis=0:  [4 6]
sum axis=1:  [3 7]


In [32]:
# Min/max
x = np.array([[1,2,3], [4,5,6]])
print ("min: ", x.min())
print ("max: ", x.max())
print ("min axis=0: ", x.min(axis=0))
print ("min axis=1: ", x.min(axis=1))

min:  1
max:  6
min axis=0:  [1 2 3]
min axis=1:  [1 4]


## Broadcasting

Here, we’re adding a vector with a scalar. Their dimensions aren’t compatible as is but how does NumPy still gives us the right result? This is where broadcasting comes in. The scalar is *broadcast* across the vector so that they have compatible shapes.

In [34]:
# Broadcasting
x = np.array([1,2]) # vector
y = np.array(3) # scalar
z = x + y
print ("z:\n", z)
v = x*5
print ("v:\n",v)

z:
 [4 5]
v:
 [ 5 10]


# To do

0. Create with all seen above, a matrix 4x5 with random integer value between 0 and 100

In [2]:
import numpy as np
matrix = np.random.randint(0, 100, (4, 5))
print(matrix)
print(matrix.shape)

[[80 42 96 76 56]
 [95 16  8 54 65]
 [14 23 82 63 70]
 [68 63 53 95 48]]
(4, 5)


1. Create a 1D array of numbers from 0 to 9 using np.arange (name it `arr`)

In [8]:
number_array = np.arange(10)
number_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Extract all odd numbers of `arr`

In [5]:
odd_number = number_array[number_array % 2 == 1]
print(odd_number)

[1 3 5 7 9]


3. Replace all odd numbers in `arr` with `-1`

In [7]:
number_array[number_array % 2 == 1] = -1
print(number_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


4. Re-create `arr` as question 1. Then create a new 1D array where you replace all odd numbers in `arr` with -1 ( without changing `arr` and its even values  by using np.where )

In [11]:
odd_number = number_array.copy()
odd_number[odd_number % 2 == 1] = -1
print(odd_number)
print(number_array)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


5. Let `q` be the following matrix

In [12]:
q = np.array([[1, 2], [3, 4]])

Compute the determinant and the inverse of `q` by using np.linalg

In [14]:
determinant_q = np.linalg.det(q) 
determinant_q

np.float64(-2.0000000000000004)

## Problème
1) Soit E un ensemble de `n` points dans le plan,
$$
    E= \lbrace (x_i, y_i); i=1,\ldots,n\rbrace
$$
On cherche à trouver la droite la plus proche expliquant ces points en utilisant la méthode de moindre carré. C'est-à-dire si on suppose `(D)` cette droite avec l'équation de 
$$
    (D): \hat{y} = a x + b
$$
On aimera que les $y_i$ et des $\hat{y}_i$ soient les plus proches possibles, c'est-à-dire, on choisit $a$ et $b$ en realisant le minimum suivant
$$
    \min ||(Y - \hat{Y})||^2_{2} ~~~~~~~~~~~~~~~~~~(1)
$$
 avec 
$$
    Y = (y_1, y_2, \ldots y_n) \text{ et } \hat{Y} = (\hat{y}_1, \hat{y}_2, \ldots \hat{y}_n)
$$
et $||~~~||_2$ est la distance euclidienne d'ordre 2 défini par:
$$ 
    || V || = \sqrt{v_1^2 + v_2^2 + \ldots + v_n^2} ~~~ \text{ pour un vecteur} ~~~ V = (v_1,v_2,\ldots,v_n) 
$$

L'objectif principal est de trouver la droite `(D)` (c'est-à-dire trouver `a` et `b`) vérifiant l'équation (1)

Le problème peut s'écrire sous forme matricielle
$$
    \hat{Y} = \left( \begin{array}{c} 
        \hat{y}_{1} \\
        \hat{y}_{2} \\
        \ldots \\
        \hat{y}_{n}
    \end{array} \right)
    = \left( \begin{array}{c} 
        b + a x_1 \\
        b + a x_2 \\
        \ldots  \\
        b + a x_n
    \end{array} \right) 
    = \left( \begin{array}{cc} 
        1 & x_1 \\
        1 & x_2 \\
        \ldots  & \\
        1 & x_n
    \end{array} \right) 
    \left( 
    \begin{array}{c} 
        b \\ 
        a 
    \end{array} 
    \right) = X \beta
$$
en posant $$\beta = \left( 
    \begin{array}{c} 
        b \\ 
        a 
    \end{array} 
    \right) $$ et 
$$
X= \left( \begin{array}{cc} 
        1 & x_1 \\
        1 & x_2 \\
        \ldots  & \\
        1 & x_n
    \end{array} \right) 
$$.

Le problème revient donc à trouver un $\beta$ qui vérifie (1), c'est-à-dire trouver le $\beta$ qui réalise le minimum de 
$$
    ||(Y - X \beta)||^2_{2} ~~~ (1)
$$
1) En faisant la remarque que $||(Y - X \beta)||^2_{2}$ est derivable par rapport à chaque élément de $\beta$ (ie `a` et `b`) , trouver alors la solution du problème.

**Indication**: le minimum d'une fonction se calcule en cherchant le point critique et vérifier si ce dernier est un minimum

2) Coder ce problème dans le plan c'est-à-dire on va donner en entrée un jeu de données E et en sortie `a` et `b` qui vérifie l'équation (1) 

**Indication**: ceci n'est qu'une implémentation de la question 1

3) Coder ce problème pour un espace de dimension supérieure c'est-à-dire que on va donner entrée un jeu de données E de la forme
   $$
    E= \lbrace (x_{i,0},x_{i,1},x_{i,2}, \ldots ,x_{i,p}, y_i); i=1,\ldots,n\rbrace
$$
et en sortie les paramètres $\beta_0,\beta_1,\ldots,\beta_p$ qui vérifie l'équation (1)

**Indication** Dans les questions précédentes on a supposé des points dans le plan (des couples (x,y)), mais supposer maintenant que ce sont des points dans des dimensions plus grande donc ( $ \hat{y} = \beta_0 + \beta_1 x_1 + \beta_2 x_2+ \ldots + \beta_p x_p)$
   

In [6]:
import numpy as np

def regression_lineaire_2d(points):
    """
    Calcule les coefficients a et b de la droite y = ax + b qui minimise l'erreur des moindres carrés.
    
    Paramètres:
    points -- liste de tuples (x, y) représentant les points du plan
    
    Retourne:
    (a, b) -- coefficients de la droite d'ajustement
    """
    # Conversion en array numpy
    points = np.array(points)
    X = points[:, 0]  # coordonnées x
    Y = points[:, 1]  # coordonnées y
    
    # Construction de la matrice X (avec colonne de 1 pour le terme constant)
    n = len(X)
    X_mat = np.column_stack((np.ones(n), X))
    
    # Calcul des coefficients (X^T X)^(-1) X^T Y
    XtX = np.dot(X_mat.T, X_mat)
    XtX_inv = np.linalg.inv(XtX)
    XtY = np.dot(X_mat.T, Y)
    beta = np.dot(XtX_inv, XtY)
    
    return beta[1], beta[0]  # retourne (a, b)

# Exemple d'utilisation
points = [(1, 2), (2, 3), (3, 5), (4, 4), (5, 6)]
a, b = regression_lineaire_2d(points)
print(f"Droite d'ajustement : y = {a:.4f}x + {b:.4f}")

Droite d'ajustement : y = 0.9000x + 1.3000


In [10]:
def regression_lineaire_multidim(X, Y):
    """
    Calcule les coefficients de la régression linéaire multiple.
    Utilise la pseudo-inverse pour gérer les matrices singulières.
    
    Paramètres:
    X -- matrice de taille (n, p) des variables explicatives
    Y -- vecteur de taille (n,) de la variable à expliquer
    
    Retourne:
    beta -- vecteur des coefficients de la régression
    """
    # Ajout de la colonne de 1 pour le terme constant
    X_mat = np.column_stack((np.ones(X.shape[0]), X))
    
    # Calcul des coefficients en utilisant la pseudo-inverse
    beta = np.linalg.pinv(X_mat) @ Y
    
    return beta

# Exemple d'utilisation
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
])
Y = np.array([5, 8, 11, 14, 17])

beta = regression_lineaire_multidim(X, Y)
print("Coefficients de la régression (β0, β1, β2, β3):", beta)

Coefficients de la régression (β0, β1, β2, β3): [ 1.         -0.66666667  0.33333333  1.33333333]


In [ ]:
def regression_lineaire_svd(X, Y):
    """
    Calcule les coefficients de la régression linéaire multiple
    en utilisant la décomposition SVD pour une meilleure stabilité numérique.
    """
    # Ajout de la colonne de 1 pour le terme constant
    X_mat = np.column_stack((np.ones(X.shape[0]), X))
    
    # Décomposition SVD
    U, s, Vt = np.linalg.svd(X_mat, full_matrices=False)
    
    # Inversion des valeurs singulières (avec un seuil pour éviter la division par zéro)
    threshold = np.finfo(s.dtype).eps * max(X_mat.shape) * s[0]
    s_inv = np.zeros_like(s)
    s_inv[s > threshold] = 1/s[s > threshold]
    
    # Calcul des coefficients
    beta = Vt.T @ (s_inv.reshape(-1, 1) * (U.T @ Y))
    
    return beta

# Utilisation
beta_svd = regression_lineaire_svd(X, Y)
print("Coefficients avec SVD (β0, β1, β2, β3):", beta_svd)

Coefficients avec SVD (β0, β1, β2, β3): [[ 8.37472630e+00  9.63028033e-01 -2.84008279e-16  0.00000000e+00]
 [-8.76279137e+00 -1.00765248e+00  2.97168553e-16  0.00000000e+00]
 [-3.88065071e-01 -4.46244484e-02  1.31602740e-17  0.00000000e+00]
 [ 7.98666123e+00  9.18403584e-01 -2.70848005e-16  0.00000000e+00]]


: 